Repository yalla-coop/curenetics, pull requests merged in 2019-10, with the labels that each got.

#55 initial ui setup
  public/index.html
  src/components/App.js
  src/components/common/.gitkeep
  src/components/common/Buttons.js
  src/components/common/Forms.js
  src/components/common/Layout.js
  src/components/common/Typography.js
  src/components/common/icons/Arrow.jsx
  src/components/common/icons/Avatar.jsx
  src/components/common/icons/Calendar.jsx
  src/components/common/icons/Chevron.jsx
  src/components/common/icons/ExportLink.jsx
  src/components/common/icons/ExternalLink.jsx
  src/components/common/icons/Keyboard.jsx
  src/components/common/icons/Marker.jsx
  src/components/common/icons/Phase.jsx
  src/components/common/icons/Plus.jsx
  src/components/common/icons/Pointer.jsx
  src/components/common/icons/Spinner.jsx
  src/components/common/icons/Stethiscope.jsx
  src/components/common/icons/TestTube.jsx
  src/components/common/icons/Tick.jsx
  src/components/common/icons/Warning.jsx
  src/components/pages/about/index.js
  src/components/pages/enter/formFields.js
  src/components/pages/enter/index.js
  src/components/pages/home/index.js
  src/components/pages/notfound/index.js
  src/components/pages/trialList/ResultDetails.js
  src/components/pages/trialList/index.js
  src/components/pages/upload/index.js
  src/styles/globalStyles.js
  src/styles/reset.css
Labels: awaiting-review, changes-requested

#63 logo
  package-lock.json
  src/components/App.js
  src/components/common/images/curenetics-logo.png
Labels: awaiting-review, changes-requested

#62 anchor link button and form field tweaks
  README.md
  src/components/common/Buttons.js
  src/components/common/Forms.js
  src/components/pages/about/index.js
  src/components/pages/enter/formFields.js
  src/components/pages/enter/index.js
  src/components/pages/home/index.js
  src/components/pages/notfound/index.js
  src/components/pages/upload/index.js
Labels: awaiting-review, changes-requested

#64 configure eslint
  .eslintrc.js
  package-lock.json
  package.json
Labels: awaiting-review

#70 Feature/trial detail page
  src/components/App.js
  src/components/common/Buttons.js
  src/components/common/Layout.js
  src/components/common/Typography.js
  src/components/common/icons/Arrow.jsx
  src/components/common/icons/ExportLink.jsx
  src/components/pages/trialDetail/CardDetails.js
  src/components/pages/trialDetail/CardField.js
  src/components/pages/trialDetail/CardSection.js
  src/components/pages/trialDetail/TrialDetailHeader.js
  src/components/pages/trialDetail/index.js
  src/styles/globalStyles.js
  src/styles/reset.css
Labels: awaiting-review

#69 Feature/select to upload
  .eslintrc.js
  src/components/App.js
  src/components/common/Buttons.js
  src/components/common/Layout.js
  src/components/common/icons/ExportLink.jsx
  src/components/pages/upload/deleteIcon.svg
  src/components/pages/upload/index.js
  src/components/pages/upload/input.js
  src/components/pages/upload/listItem.js
  src/components/pages/upload/uploadStyles.js
  src/helpers.js
Labels: awaiting-review

#67 Feature/list patients
  package-lock.json
  package.json
  src/components/App.js
  src/components/common/Buttons.js
  src/components/common/Forms.js
  src/components/common/Layout.js
  src/components/common/README.md
  src/components/common/Typography.js
  src/components/common/icons/Arrow.jsx
  src/components/common/icons/Plus.jsx
  src/components/common/icons/Spinner.jsx
  src/components/pages/about/index.js
  src/components/pages/enter/index.js
  src/components/pages/home/index.js
  src/components/pages/notfound/index.js
  src/components/pages/patientList/addOptionsFunc.js
  src/components/pages/patientList/index.js
  src/components/pages/patientList/patientDummyData.js
  src/components/pages/patientList/patientField.js
  src/components/pages/patientList/patientFooter.js
  src/components/pages/patientList/patientIntro.js
  src/components/pages/patientList/style.js
  src/components/pages/trialDetail/CardDetails.js
  src/components/pages/trialDetail/CardField.js
  src/components/pages/trialDetail/CardSection.js
  src/components/pages/trialDetail/TrialDetailHeader.js
  src/components/pages/trialDetail/index.js
  src/components/pages/upload/index.js
  src/styles/globalStyles.js
  src/styles/reset.css
Labels: awaiting-review

#73 Loading component
  package-lock.json
  src/components/common/Loading.js
  src/components/pages/upload/index.js
Labels: awaiting-review

#76 netlify redirects for routes outside of menu
  public/_redirects
Labels: awaiting-review

#77 Feature/enter patients
  src/components/App.js
  src/components/common/Layout.js
  src/components/common/icons/AddCercle.jsx
  src/components/common/icons/DeleteCercle.jsx
  src/components/pages/enterPatients/PatientCards.js
  src/components/pages/enterPatients/index.js
  src/components/pages/enterPatients/patientField.js
  src/components/pages/enterPatients/patientIntro.js
  src/components/pages/patientList/style.js
Labels: awaiting-review

#101 About page copy
  package-lock.json
  src/components/pages/about/index.js
Labels: awaiting-review

#95 add the support for IE 11
  package-lock.json
  package.json
  src/index.js
Labels: awaiting-review

#100 Fix/patient list 86
  src/components/pages/patientList/addOptionsFunc.js
  src/components/pages/patientList/patientField.js
  src/components/pages/patientList/style.js
Labels: awaiting-review

#102 About-ed2-Sola
  src/components/pages/about/index.js
Labels: awaiting-review

#79 Feature/view match trials
  src/components/App.js
  src/components/common/icons/ExportLink.jsx
  src/components/common/icons/TestTube.jsx
  src/components/common/useIsSmall.js
  src/components/pages/matchTrial/cardMatch.js
  src/components/pages/matchTrial/dummyData.js
  src/components/pages/matchTrial/headerMatch.js
  src/components/pages/matchTrial/index.js
  src/components/pages/matchTrial/style.js
  src/components/pages/matchTrial/table.js
Labels: awaiting-review

#91 Trials api JSON
  Results-10-10-19.json
  dummydata/Results-12-10-19.json
Labels: awaiting-review

#105 Feature/enter records button
  src/components/App.js
  src/components/pages/enterPatients/index.js
  src/components/pages/enterPatients/patientField.js
  src/components/pages/home/index.js
  src/components/pages/patientList/addOptionsFunc.js
Labels: awaiting-review

#104 add sort functionality to trial list page
  src/components/pages/trialDetail/TrialDetailHeader.js
  src/components/pages/trialDetail/index.js
Labels: awaiting-review

#96 Feature/exports
  package-lock.json
  package.json
  src/assets/calendar.png
  src/assets/calendarImg.png
  src/components/App.js
  src/components/common/fonts/Roboto-Bold.ttf
  src/components/common/fonts/Roboto-Light.ttf
  src/components/common/fonts/Roboto-Regular.ttf
  src/components/common/images/avatar.png
  src/components/common/images/calendar.png
  src/components/common/images/marker.png
  src/components/common/images/phase.png
  src/components/common/images/plus.png
  src/components/common/images/stethiscope.png
  src/components/common/images/test-tube.png
  src/components/common/images/tick-green.png
  src/components/common/images/tick.png
  src/components/common/pdf/pdfIcons.js
  src/components/common/pdf/pdfStyles.js
  src/components/common/pdf/pdfTemplate.js
  src/components/common/pdf/singleTrial/index.js
  src/components/common/pdf/singleTrial/location.js
  src/components/common/pdf/singleTrial/matchHeader.js
  src/components/common/pdf/singleTrial/matchTable.js
  src/components/pages/matchTrial/cardMatch.js
  src/components/pages/matchTrial/index.js
  src/components/pages/matchTrial/style.js
Labels: awaiting-review

#97 Feature/patient original file
  .eslintrc.js
  package-lock.json
  package.json
  src/components/App.js
  src/components/pages/patientList/addOptionsFunc.js
  src/components/pages/patientList/index.js
  src/components/pages/patientList/patientOrginalFile.js
  src/components/pages/upload/index.js
  src/dummydata/patientdata.json
Labels: awaiting-review

#112 remvoe duplicate pages
  dummydata/Results-10-10-19.json
  src/components/App.js
  src/components/pages/enter/formFields.js
  src/components/pages/enter/index.js
  src/components/pages/trialDetail/index.js
  src/components/pages/trialList/CardSection.js
  src/components/pages/trialList/ResultDetails.js
  src/components/pages/trialList/TrialDetailHeader.js
  src/components/pages/trialList/index.js
Labels: awaiting-review

#115 connect find trial with filter function
  src/components/pages/enterPatients/index.js
  src/components/pages/trialList/CardSection.js
  src/components/pages/trialList/TrialDetailHeader.js
  src/components/pages/trialList/index.js
  src/helpers/filter-helpers.js
  src/helpers/filter.js
Labels: awaiting-review

#117 link on index page
  package-lock.json
  src/components/pages/home/index.js
Labels: don't merge

#124 spelling correction
  src/components/pages/enterPatients/patientIntro.js
  src/components/pages/trialList/TrialDetailHeader.js
Labels: awaiting-review

#122 small edits to upload component
  src/components/pages/upload/delete-cross.svg
  src/components/pages/upload/listItem.js
Labels: awaiting-review

#123 Feature/modal
  src/components/pages/upload/modal.js
Labels: awaiting-review

#119 Filtered trial details
  .eslintrc.js
  package-lock.json
  public/manifest.json
  src/components/App.js
  src/components/common/icons/ExternalLink.jsx
  src/components/common/pdf/pdfTemplate.js
  src/components/common/pdf/singleTrial/index.js
  src/components/common/pdf/singleTrial/location.js
  src/components/common/pdf/singleTrial/matchHeader.js
  src/components/common/pdf/singleTrial/matchTable.js
  src/components/common/pdf/singleTrial/renderBasedObj-helper.js
  src/components/pages/matchTrial/cardMatch.js
  src/components/pages/matchTrial/headerMatch.js
  src/components/pages/matchTrial/index.js
  src/components/pages/matchTrial/style.js
  src/components/pages/matchTrial/table.js
  src/components/pages/patientList/PatientMatchButton.js
  src/components/pages/patientList/index.js
  src/components/pages/patientList/patientIntro.js
  src/components/pages/trialList/CardSection.js
  src/components/pages/trialList/TrialDetailHeader.js
  src/components/pages/trialList/index.js
  src/components/pages/trialList/trialList-helpers.js
  src/constants/filter-criteria.js
  src/constants/urls.js
  src/dummydata/Results-12-10-19.json
  src/helpers/eligibility.js
  src/helpers/filter-helpers.js
  src/helpers/filter.js
Labels: awaiting-review

#139 Filter tweaks
  src/components/pages/patientList/addOptionsFunc.js
  src/helpers/filter-helpers.js
  src/helpers/filter.js
Labels: awaiting-review

#143 add favicon
  public/favicon.png
  public/index.html
Labels: awaiting-review

#148 add fileName to the pdf files
  src/components/common/pdf/singleTrial/index.js
  src/components/common/pdf/singleTrial/matchHeader.js
  src/components/pages/matchTrial/headerMatch.js
  src/components/pages/matchTrial/style.js
  src/helpers/filter.js
Labels: awaiting-review

#145 replace antd loading with a page loading
  src/components/common/Loading.js
  src/components/pages/trialList/index.js
Labels: awaiting-review

#127 readme #93
  README.md
Labels: awaiting-review
